name: 'Build Prep (Checkout, SSH, Toolchains)'
description: 'Prepare build environment: checkout repos, setup SSH, install toolchains'

inputs:
  ref:
    description: 'Git reference to build'
    required: true
  is_release:
    description: 'Whether this is a release build'
    required: false
    default: 'false'
  platform:
    description: 'Platform being built (macos, windows, linux)'
    required: true
  arch:
    description: 'Architecture being built (aarch64, x86_64, i686)'
    required: true

  private_repo_ssh_key:
    description: 'Deploy key for alain1405/rostoc'
    required: true

  apple_certificate:
    description: 'Base64-encoded Apple signing certificate'
    required: false
    default: ''

  apple_certificate_password:
    description: 'Password for Apple signing certificate'
    required: false
    default: ''

  apple_signing_identity:
    description: 'Apple signing identity name'
    required: false
    default: ''

  apple_team_id:
    description: 'Apple Developer Team ID'
    required: false
    default: ''

  apple_id:
    description: 'Apple ID for notarization'
    required: false
    default: ''

  apple_app_specific_password:
    description: 'App-specific password for Apple ID'
    required: false
    default: ''

outputs:
  pnpm_store_path:
    description: 'Path to pnpm store'
    value: ${{ steps.pnpm-store.outputs.STORE_PATH }}
  version:
    description: 'Extracted version from tauri.conf.json'
    value: ${{ steps.extract_version.outputs.version }}
  release_version:
    description: 'Release version (if is_release)'
    value: ${{ env.RELEASE_VERSION }}

runs:
  using: 'composite'
  steps:
    - name: Checkout updates repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup SSH agent for private repo
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.private_repo_ssh_key }}

    - name: Add GitHub to known_hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout private repo (read-only)
      uses: actions/checkout@v4
      with:
        repository: alain1405/rostoc
        ref: ${{ inputs.ref }}
        ssh-key: ${{ inputs.private_repo_ssh_key }}
        path: private-src
        fetch-depth: 0

    - name: Force pull latest commit from private repo
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Force pulling latest from ${{ inputs.ref }}"
        git fetch origin "${{ inputs.ref }}"
        git reset --hard FETCH_HEAD
        CURRENT_SHA=$(git rev-parse HEAD)
        echo "::notice::Building at commit $CURRENT_SHA"
        echo "::endgroup::"

    - name: Debug Cargo.toml content
      working-directory: private-src
      shell: bash
      run: |
        echo "::group::Cargo.toml content (first 10 lines)"
        head -10 src-tauri/Cargo.toml || echo "File not found"
        echo "::endgroup::"
        echo "::group::Full path check"
        ls -la src-tauri/Cargo.toml || echo "File not found"
        pwd
        ls -la src-tauri/ || echo "Directory not found"
        echo "::endgroup::"

    - name: Capture release version
      if: ${{ inputs.is_release == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        REF="${{ inputs.ref }}"
        VERSION=${REF#v}
        if [[ -z "$VERSION" ]]; then
          echo "::error::Unable to derive release version from ref '$REF'" >&2
          exit 1
        fi
        echo "RELEASE_VERSION=$VERSION" >> "$GITHUB_ENV"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Python 3.11 (default x64)
      if: ${{ !(inputs.platform == 'windows' && inputs.arch == 'i686') }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Python 3.11 (Windows x86)
      if: ${{ inputs.platform == 'windows' && inputs.arch == 'i686' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x86'

    - name: Enable Corepack (pnpm)
      shell: bash
      run: corepack enable

    - name: Derive pnpm store path
      id: pnpm-store
      shell: bash
      run: |
        set -euo pipefail
        cd private-src
        echo "[INFO] pnpm version: $(pnpm --version || true)" >&2
        STORE_PATH=$(pnpm store path 2>/dev/null | tr -d '\r' || true)
        if [ -z "${STORE_PATH}" ]; then
          echo "[WARN] pnpm store path empty; falling back to default ~/.pnpm-store" >&2
          STORE_PATH="$HOME/.pnpm-store"
        fi
        mkdir -p "$STORE_PATH" || true
        echo "Using STORE_PATH=$STORE_PATH" >&2
        echo "STORE_PATH=$STORE_PATH" >> "$GITHUB_OUTPUT"

    - name: Compute dependency hashes
      id: dependency-hashes
      shell: bash
      run: scripts/ci/hash_lockfiles.sh private-src

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
        key: pnpm-${{ runner.os }}-${{ steps.dependency-hashes.outputs.pnpm }}
        restore-keys: pnpm-${{ runner.os }}-

    - name: Install uv (Python package manager)
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        curl -LsSf https://astral.sh/uv/install.sh | sh
        UV_DIR="$HOME/.local/bin"
        echo "UV_BIN=$UV_DIR" >> "$GITHUB_ENV"
        echo "$UV_DIR" >> "$GITHUB_PATH"
        # Make uv immediately available in this step
        PATH="$UV_DIR:$PATH"
        if command -v cygpath >/dev/null 2>&1; then
          WIN_UV_DIR=$(cygpath -w "$UV_DIR")
          echo "$WIN_UV_DIR" >> "$GITHUB_PATH"
        fi
        uv --version

    - name: Cache Python wheels
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
          ~/.cache/uv
          ~/Library/Caches/uv
        key: python-wheel-${{ runner.os }}-${{ steps.dependency-hashes.outputs.uv }}
        restore-keys: |
          python-wheel-${{ runner.os }}-

    - name: '[macOS] Install Apple signing certificate'
      if: ${{ inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      env:
        APPLE_CERTIFICATE: ${{ inputs.apple_certificate }}
        APPLE_CERTIFICATE_PASSWORD: ${{ inputs.apple_certificate_password }}
        APPLE_SIGNING_IDENTITY: ${{ inputs.apple_signing_identity }}
        APPLE_TEAM_ID: ${{ inputs.apple_team_id }}
        APPLE_ID: ${{ inputs.apple_id }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ inputs.apple_app_specific_password }}
      run: |
        set -euo pipefail
        scripts/macos/install_signing_certificate.sh

    - name: '[macOS] Debug signing keychain state'
      if: ${{ inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      env:
        APPLE_SIGNING_IDENTITY: ${{ inputs.apple_signing_identity }}
      run: |
        set -euo pipefail
        echo "[DEBUG] Listing configured keychains" >&2
        security list-keychains || true
        echo "[DEBUG] Available signing identities" >&2
        security find-identity -v -p codesigning || true
        if [ -n "${APPLE_SIGNING_IDENTITY:-}" ]; then
          echo "[DEBUG] Matching certificate summary for ${APPLE_SIGNING_IDENTITY}" >&2
          security find-certificate -Z -a -c "$APPLE_SIGNING_IDENTITY" 2>/dev/null | grep -E 'SHA-1|SHA-256|"' || true
        else
          echo "[DEBUG] APPLE_SIGNING_IDENTITY not provided" >&2
        fi

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies and build artifacts
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: private-src
        # Removed shared-key to let cache auto-invalidate on Cargo.toml changes
        # Each platform will have its own cache based on Cargo.toml+Cargo.lock
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Extract version
      id: extract_version
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        VERSION=$(jq -r '.version' src-tauri/tauri.conf.json)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "[INFO] Extracted version: $VERSION"
