name: 'Build Compile (Download Python, Build, Stage)'
description: 'Download Python runtime, install JS deps, stamp version, compile application'

inputs:
  platform:
    description: 'Platform being built (macos, windows, linux)'
    required: true
  arch:
    description: 'Architecture being built (aarch64, x86_64, i686)'
    required: true
  is_release:
    description: 'Whether this is a release build'
    required: false
    default: 'false'
  apple_signing_identity:
    description: 'Apple signing identity (macOS signing)'
    required: false
  apple_team_id:
    description: 'Apple Team ID (macOS signing)'
    required: false
  apple_id:
    description: 'Apple ID (notarytool)'
    required: false
  apple_app_specific_password:
    description: 'App-specific password for Apple ID (notarytool)'
    required: false
  tauri_signing_private_key:
    description: 'Tauri updater signing key'
    required: false
  tauri_signing_private_key_password:
    description: 'Password for the Tauri updater signing key'
    required: false

outputs:
  build_command:
    description: 'Build command used'
    value: ${{ steps.platform_config.outputs.build_command }}
  target:
    description: 'Rust target triple'
    value: ${{ steps.platform_config.outputs.target }}

runs:
  using: 'composite'
  steps:
    - name: Initialize platform-specific config
      id: platform_config
      shell: bash
      run: |
        set -euo pipefail

        # Add --mode development and --features devtools for staging builds
        # --mode development: Enables TanStack Router DevTools (Vite MODE=development)
        # --features devtools: Enables Tauri WebView DevTools (right-click inspect)
        MODE_FLAG=""
        FEATURES_FLAG=""
        CONFIG_FLAG=""
        if [ "${ROSTOC_APP_VARIANT:-production}" == "staging" ]; then
          MODE_FLAG="--mode development"
          FEATURES_FLAG="--features devtools"
          CONFIG_FLAG="--config src-tauri/tauri.staging.conf.json"
          # Export for build.py to pass to generate_python_config.py
          echo "TAURI_CONFIG_FLAG=src-tauri/tauri.staging.conf.json" >> "$GITHUB_ENV"
        fi

        case "${{ inputs.platform }}" in
          macos)
            {
              echo "build_command=python scripts/build.py --locked $MODE_FLAG $FEATURES_FLAG"
              echo "artifact_extension=tar.gz"
              echo "test_smoke=true"
              if [ "${{ inputs.arch }}" == "x86_64" ]; then
                echo "target=x86_64-apple-darwin"
                echo "py_url_fragment=macos-x64"
              else
                echo "target=aarch64-apple-darwin"
                echo "py_url_fragment=macos-arm64"
              fi
            } >> "$GITHUB_OUTPUT"
            ;;
          windows)
            {
              if [ "${{ inputs.arch }}" == "x86_64" ]; then
                echo "build_command=python scripts/build.py --locked --bundles msi $MODE_FLAG $FEATURES_FLAG"
                echo "target=x86_64-pc-windows-msvc"
                echo "py_url_fragment=windows-x64"
              else
                # For 32-bit Windows, pass --target to Tauri CLI so WiX creates 32-bit MSI
                echo "build_command=python scripts/build.py --locked --bundles msi --target i686-pc-windows-msvc $MODE_FLAG $FEATURES_FLAG"
                echo "target=i686-pc-windows-msvc"
                echo "py_url_fragment=windows-x86"
              fi
              echo "artifact_extension=msi"
              echo "test_smoke=true"
            } >> "$GITHUB_OUTPUT"
            ;;
          linux)
            {
              echo "build_command=python scripts/build.py --locked --bundles appimage $MODE_FLAG $FEATURES_FLAG"
              echo "artifact_extension=AppImage"
              echo "test_smoke=true"
              echo "target=x86_64-unknown-linux-gnu"
              echo "py_url_fragment=linux-x64"
            } >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "::error::Unknown platform: ${{ inputs.platform }}"
            exit 1
            ;;
        esac

    - name: '[macOS Intel] Confirm runner architecture'
      if: ${{ inputs.arch == 'x86_64' && inputs.platform == 'macos' }}
      shell: bash
      run: |
        RUNNER_ARCH=$(uname -m)
        if [ "$RUNNER_ARCH" != "x86_64" ]; then
          echo "::warning::Runner reports architecture $RUNNER_ARCH but matrix specifies x86_64"
        fi
        echo "[INFO] macOS runner architecture: $RUNNER_ARCH"
        uname -a

    - name: '[macOS Intel] Clear stale pyembed (force x86_64 download)'
      if: ${{ inputs.arch == 'x86_64' && inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        if [ -d src-tauri/pyembed ]; then
          echo "[INFO] Removing existing src-tauri/pyembed to avoid arm64 leftovers"
          rm -rf src-tauri/pyembed
        fi

    - name: '[Windows x86] Verify cross-compile capability'
      if: ${{ inputs.arch == 'i686' && inputs.platform == 'windows' }}
      shell: bash
      run: |
        echo "[INFO] Windows x86 (32-bit) build via MSVC cross-compile on x64 runner"
        rustup target add i686-pc-windows-msvc
        echo "✅ i686-pc-windows-msvc target installed"
        echo "CARGO_BUILD_TARGET=i686-pc-windows-msvc" >> "$GITHUB_ENV"
        echo "✅ CARGO_BUILD_TARGET environment variable set for automatic cross-compilation"

    - name: '[Linux] Install system dependencies for AppImage'
      if: ${{ inputs.platform == 'linux' }}
      shell: bash
      run: |
        sudo apt-get update -qq
        # Tauri v2 + WebKit 4.1 dependencies for AppImage
        # libfuse2 is required by AppImage tools (linuxdeploy is itself an AppImage)
        # librsvg2-dev and libayatana-appindicator3-dev are required for proper GTK bundling
        # libwebp-dev is required for image processing support
        sudo apt-get install -y \
          libssl-dev \
          libffi-dev \
          libglib2.0-0 \
          libglib2.0-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libjavascriptcoregtk-4.1-dev \
          librsvg2-dev \
          libayatana-appindicator3-dev \
          libwebp-dev \
          patchelf \
          pkg-config \
          libx11-6 \
          fuse3 \
          libfuse2
        echo "✅ AppImage build dependencies installed"

    - name: Download embedded Python
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        case "${{ inputs.platform }}" in
          macos)
            if [ "${{ inputs.arch }}" = "x86_64" ]; then
              PYTHON_TARGET="x86_64-apple-darwin"
            else
              PYTHON_TARGET="aarch64-apple-darwin"
            fi
            PYTHON_TARGET="$PYTHON_TARGET" bash scripts/macos/download-py.sh
            ;;
          windows)
            if [ "${{ inputs.arch }}" = "i686" ]; then
              PYTHON_TARGET="i686-pc-windows-msvc"
            else
              PYTHON_TARGET="x86_64-pc-windows-msvc"
            fi
            PYTHON_TARGET="$PYTHON_TARGET" pwsh scripts/windows/download-py.ps1
            ;;
          linux)
            PYTHON_TARGET="x86_64-unknown-linux-gnu" bash scripts/linux/download-py.sh
            ;;
        esac

    - name: Install JS dependencies
      working-directory: private-src
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Stamp build version
      working-directory: private-src
      shell: bash
      env:
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        set -euo pipefail
        if [[ -n "${RELEASE_VERSION:-}" ]]; then
          scripts/ci/stamp_dev_version.sh --version "$RELEASE_VERSION"
        else
          scripts/ci/stamp_dev_version.sh
        fi

    - name: Set variant-specific Tauri config flag
      shell: bash
      run: |
        case "${ROSTOC_APP_VARIANT:-production}" in
          staging)
            echo "TAURI_CONFIG_FLAG=src-tauri/tauri.staging.conf.json" >> "$GITHUB_ENV"
            ;;
          dev)
            echo "TAURI_CONFIG_FLAG=src-tauri/tauri.dev.conf.json" >> "$GITHUB_ENV"
            ;;
          production)
            echo "TAURI_CONFIG_FLAG=" >> "$GITHUB_ENV"
            ;;
          *)
            echo "::warning::Unknown variant '$ROSTOC_APP_VARIANT', defaulting to production"
            echo "TAURI_CONFIG_FLAG=" >> "$GITHUB_ENV"
            ;;
        esac
        echo "[INFO] TAURI_CONFIG_FLAG=${TAURI_CONFIG_FLAG:-<empty>}"

    - name: Generate Python config (before runtime staging)
      working-directory: private-src
      shell: bash
      run: scripts/ci/generate_and_verify_config.sh

    - name: '[macOS] Stage Python runtime (before Tauri build/sign)'
      if: ${{ inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      run: scripts/ci/stage_and_verify_runtime.sh

    - name: '[macOS] Sign Python binaries and libraries (before Tauri build)'
      if: ${{ inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      env:
        APPLE_SIGNING_IDENTITY: ${{ inputs.apple_signing_identity }}
      run: scripts/ci/sign_python_runtime.sh

    - name: '[macOS] Verify generated_config.py after signing'
      if: ${{ inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      run: scripts/ci/verify_config_after_signing.sh

    - name: Validate version matches tag (release builds only)
      if: ${{ inputs.is_release == 'true' }}
      working-directory: private-src
      shell: bash
      env:
        GITHUB_REF: ${{ github.ref }}
      run: scripts/ci/validate_release_version.sh

    - name: Build application
      working-directory: private-src
      shell: bash
      env:
        # Variant configuration (must be set for Rust compile-time option_env! macro)
        ROSTOC_APP_VARIANT: ${{ env.ROSTOC_APP_VARIANT }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri_signing_private_key }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri_signing_private_key_password }}
        APPLE_SIGNING_IDENTITY: ${{ inputs.apple_signing_identity }}
        APPLE_TEAM_ID: ${{ inputs.apple_team_id }}
        APPLE_ID: ${{ inputs.apple_id }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ inputs.apple_app_specific_password }}
        ENABLE_RUNTIME_CACHE: '1'
        UV_DISABLE_WORKSPACE: '1'
        UV_PROJECT_ENVIRONMENT: 'shared'
        RUST_TARGET: ${{ steps.platform_config.outputs.target }}
        CROSS_COMPILE_ARGS: ${{ steps.platform_config.outputs.cross_compile_args || '' }}
        # Skip rosi (and its pandas dependency) on optional 32-bit Windows builds
        SKIP_ROSI: ${{ inputs.platform == 'windows' && inputs.arch == 'i686' && '1' || '' }}
        # Linux AppImage workarounds for FUSE and linuxdeploy issues
        APPIMAGE_EXTRACT_AND_RUN: ${{ inputs.platform == 'linux' && '1' || '' }}
        NO_STRIP: ${{ inputs.platform == 'linux' && '1' || '' }}
        OUTPUT: ${{ inputs.platform == 'linux' && '2' || '' }}
        VERBOSE: ${{ inputs.platform == 'linux' && '1' || '' }}
      run: scripts/ci/execute_build.sh "${{ inputs.platform }}" "${{ inputs.arch }}" "${{ steps.platform_config.outputs.build_command }}"
