name: 'Build Tests (Smoke tests for all platforms)'
description: 'Run runtime and GUI smoke tests, upload diagnostics'

inputs:
  platform:
    description: 'Platform being built (macos, windows, linux)'
    required: true
  arch:
    description: 'Architecture being built (aarch64, x86_64, i686)'
    required: true
  app_path:
    description: 'Path to app bundle (macOS only)'
    required: false
  python_path:
    description: 'Path to embedded Python (macOS only)'
    required: false
  variant:
    description: 'Build variant (production|staging|dev)'
    required: false
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: '[macOS] Runtime smoke test'
      if: ${{ inputs.platform == 'macos' && inputs.app_path != '' }}
      working-directory: private-src
      shell: bash
      env:
        APP_BUNDLE: ${{ inputs.app_path }}
        PYBIN_HINT: ${{ inputs.python_path }}
      run: |
        set -euo pipefail
        if [ -z "${APP_BUNDLE}" ]; then
          echo "::warning::APP_BUNDLE not set, skipping macOS runtime smoke test"
          exit 0
        fi
        if [[ "${APP_BUNDLE}" == /* ]]; then
          ABS_APP="${APP_BUNDLE}"
        else
          ABS_APP="$GITHUB_WORKSPACE/private-src/${APP_BUNDLE}"
        fi
        if [ ! -d "$ABS_APP" ]; then
          echo "::warning::App bundle not found at $ABS_APP, skipping runtime test"
          exit 0
        fi
        PYBIN="${PYBIN_HINT}"
        if [[ -n "$PYBIN" && "$PYBIN" != /* ]]; then
          PYBIN="$GITHUB_WORKSPACE/private-src/$PYBIN"
        fi
        if [ -z "$PYBIN" ] || [ ! -x "$PYBIN" ]; then
          echo "::warning::Embedded Python not found at $PYBIN, skipping runtime test"
          exit 0
        fi
        echo "[INFO] Running runtime smoke test: $PYBIN"
        "$PYBIN" scripts/ci/unified_smoke_validator.py runtime \
          --platform mac \
          --comprehensive \
          --require-manifest \
          --debug-json macos_runtime_smoke_debug.json \
          --strict

    - name: '[macOS] GUI smoke test (non-fatal)'
      if: ${{ inputs.platform == 'macos' }}
      working-directory: private-src
      shell: bash
      env:
        PYBIN_HINT: ${{ inputs.python_path }}
      run: |
        set -euo pipefail
        ABS_APP="${{ inputs.app_path }}"
        if [ -z "$ABS_APP" ]; then
          echo "::warning::App path not provided, skipping GUI smoke test"
          exit 0
        fi
        PYBIN="${PYBIN_HINT}"
        if [[ -n "$PYBIN" && "$PYBIN" != /* ]]; then
          PYBIN="$GITHUB_WORKSPACE/private-src/$PYBIN"
        fi
        if [ -z "$PYBIN" ] || [ ! -x "$PYBIN" ]; then
          echo "::warning::Embedded Python not found, skipping GUI smoke test"
          exit 0
        fi
        echo "[INFO] Running GUI smoke test with 10s timeout"
        "$PYBIN" scripts/ci/unified_smoke_validator.py gui \
          --platform mac \
          --timeout 10 \
          --debug-json macos_gui_smoke_debug.json || {
          exitcode=$?
          echo "[WARN] GUI smoke test failed (non-fatal): exit code $exitcode"
          exit 0
        }

    - name: '[Windows x86] Runtime smoke test (cross-compile validation)'
      if: ${{ inputs.platform == 'windows' && inputs.arch == 'i686' }}
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        PYTHON_PATH=$(python3 scripts/ci/get_runtime_path.py python_path windows)
        PYBIN=$(find target -type f -path "*/$PYTHON_PATH" -print -quit || true)
        if [ -z "$PYBIN" ]; then
          echo "[WARN] Embedded python.exe not found at canonical location for x86 build"
          exit 0
        fi
        echo "[INFO] Running x86 runtime smoke test: $PYBIN" >&2
        "$PYBIN" scripts/ci/unified_smoke_validator.py runtime \
          --platform windows \
          --comprehensive \
          --require-manifest \
          --debug-json windows_x86_runtime_smoke_debug.json \
          --strict || {
          exitcode=$?
          echo "[WARN] x86 smoke test failed (optional platform, continuing): exit code $exitcode"
          exit 0
        }

    - name: '[Linux] Runtime smoke test'
      if: ${{ inputs.platform == 'linux' }}
      working-directory: private-src
      shell: bash
      run: |
        set -euo pipefail
        PYTHON_PATH=$(python3 scripts/ci/get_runtime_path.py python_path unix)
        PYBIN=$(find target -type f -path "*/$PYTHON_PATH" -print -quit || true)
        if [ -z "$PYBIN" ]; then
          echo "[WARN] Embedded python not found at canonical location for Linux build"
          exit 0
        fi
        echo "[INFO] Running Linux runtime smoke test: $PYBIN" >&2
        "$PYBIN" scripts/ci/unified_smoke_validator.py runtime \
          --platform linux \
          --comprehensive \
          --require-manifest \
          --debug-json linux_runtime_smoke_debug.json \
          --strict || {
          exitcode=$?
          echo "[WARN] Linux smoke test failed (optional platform, continuing): exit code $exitcode"
          exit 0
        }

    - name: Upload macOS smoke diagnostics
      if: ${{ inputs.platform == 'macos' && always() }}
      uses: actions/upload-artifact@v4
      with:
        name: smoke-debug-${{ inputs.variant }}-${{ inputs.platform }}-${{ inputs.arch }}
        path: |
          private-src/macos_runtime_smoke_debug.json
          private-src/macos_gui_smoke_debug.json
        if-no-files-found: warn

    - name: Upload Windows x86 smoke diagnostics
      if: ${{ inputs.platform == 'windows' && inputs.arch == 'i686' && always() }}
      uses: actions/upload-artifact@v4
      with:
        name: smoke-debug-${{ inputs.variant }}-${{ inputs.platform }}-${{ inputs.arch }}
        path: |
          private-src/windows_x86_runtime_smoke_debug.json
        if-no-files-found: warn

    - name: Upload Linux smoke diagnostics
      if: ${{ inputs.platform == 'linux' && always() }}
      uses: actions/upload-artifact@v4
      with:
        name: smoke-debug-${{ inputs.variant }}-${{ inputs.platform }}-${{ inputs.arch }}
        path: |
          private-src/linux_runtime_smoke_debug.json
        if-no-files-found: warn

    - name: Upload build logs (post-tests)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-post-tests-${{ inputs.variant }}-${{ inputs.platform }}-${{ inputs.arch }}
        path: |
          private-src/build-*.log
        if-no-files-found: warn
